#__ error_codes

"""
- `0` - OK
- `1` - UNSUPPORTED\\_METHOD
- `2` - UNSUPPORTED\\_PARAMETER
- `3` - UNEXPECTED\\_END\\_OF\\_FILE
- `4` - EXPECTED\\_END\\_OF\\_FILE
- `6` - CANNOT\\_PARSE\\_TEXT
- `7` - INCORRECT\\_NUMBER\\_OF\\_COLUMNS
- `8` - THERE\\_IS\\_NO\\_COLUMN
- `9` - SIZES\\_OF\\_COLUMNS\\_DOESNT\\_MATCH
- `10` - NOT\\_FOUND\\_COLUMN\\_IN\\_BLOCK
- `11` - POSITION\\_OUT\\_OF\\_BOUND
- `12` - PARAMETER\\_OUT\\_OF\\_BOUND
- `13` - SIZES\\_OF\\_COLUMNS\\_IN\\_TUPLE\\_DOESNT\\_MATCH
- `15` - DUPLICATE\\_COLUMN
- `16` - NO\\_SUCH\\_COLUMN\\_IN\\_TABLE
- `19` - SIZE\\_OF\\_FIXED\\_STRING\\_DOESNT\\_MATCH
- `20` - NUMBER\\_OF\\_COLUMNS\\_DOESNT\\_MATCH
- `23` - CANNOT\\_READ\\_FROM\\_ISTREAM
- `24` - CANNOT\\_WRITE\\_TO\\_OSTREAM
- `25` - CANNOT\\_PARSE\\_ESCAPE\\_SEQUENCE
- `26` - CANNOT\\_PARSE\\_QUOTED\\_STRING
- `27` - CANNOT\\_PARSE\\_INPUT\\_ASSERTION\\_FAILED
- `28` - CANNOT\\_PRINT\\_FLOAT\\_OR\\_DOUBLE\\_NUMBER
- `32` - ATTEMPT\\_TO\\_READ\\_AFTER\\_EOF
- `33` - CANNOT\\_READ\\_ALL\\_DATA
- `34` - TOO\\_MANY\\_ARGUMENTS\\_FOR\\_FUNCTION
- `35` - TOO\\_FEW\\_ARGUMENTS\\_FOR\\_FUNCTION
- `36` - BAD\\_ARGUMENTS
- `37` - UNKNOWN\\_ELEMENT\\_IN\\_AST
- `38` - CANNOT\\_PARSE\\_DATE
- `39` - TOO\\_LARGE\\_SIZE\\_COMPRESSED
- `40` - CHECKSUM\\_DOESNT\\_MATCH
- `41` - CANNOT\\_PARSE\\_DATETIME
- `42` - NUMBER\\_OF\\_ARGUMENTS\\_DOESNT\\_MATCH
- `43` - ILLEGAL\\_TYPE\\_OF\\_ARGUMENT
- `44` - ILLEGAL\\_COLUMN
- `46` - UNKNOWN\\_FUNCTION
- `47` - UNKNOWN\\_IDENTIFIER
- `48` - NOT\\_IMPLEMENTED
- `49` - LOGICAL\\_ERROR
- `50` - UNKNOWN\\_TYPE
- `51` - EMPTY\\_LIST\\_OF\\_COLUMNS\\_QUERIED
- `52` - COLUMN\\_QUERIED\\_MORE\\_THAN\\_ONCE
- `53` - TYPE\\_MISMATCH
- `55` - STORAGE\\_REQUIRES\\_PARAMETER
- `56` - UNKNOWN\\_STORAGE
- `57` - TABLE\\_ALREADY\\_EXISTS
- `58` - TABLE\\_METADATA\\_ALREADY\\_EXISTS
- `59` - ILLEGAL\\_TYPE\\_OF\\_COLUMN\\_FOR\\_FILTER
- `60` - UNKNOWN\\_TABLE
- `62` - SYNTAX\\_ERROR
- `63` - UNKNOWN\\_AGGREGATE\\_FUNCTION
- `68` - CANNOT\\_GET\\_SIZE\\_OF\\_FIELD
- `69` - ARGUMENT\\_OUT\\_OF\\_BOUND
- `70` - CANNOT\\_CONVERT\\_TYPE
- `71` - CANNOT\\_WRITE\\_AFTER\\_END\\_OF\\_BUFFER
- `72` - CANNOT\\_PARSE\\_NUMBER
- `73` - UNKNOWN\\_FORMAT
- `74` - CANNOT\\_READ\\_FROM\\_FILE\\_DESCRIPTOR
- `75` - CANNOT\\_WRITE\\_TO\\_FILE\\_DESCRIPTOR
- `76` - CANNOT\\_OPEN\\_FILE
- `77` - CANNOT\\_CLOSE\\_FILE
- `78` - UNKNOWN\\_TYPE\\_OF\\_QUERY
- `79` - INCORRECT\\_FILE\\_NAME
- `80` - INCORRECT\\_QUERY
- `81` - UNKNOWN\\_DATABASE
- `82` - DATABASE\\_ALREADY\\_EXISTS
- `83` - DIRECTORY\\_DOESNT\\_EXIST
- `84` - DIRECTORY\\_ALREADY\\_EXISTS
- `85` - FORMAT\\_IS\\_NOT\\_SUITABLE\\_FOR\\_INPUT
- `86` - RECEIVED\\_ERROR\\_FROM\\_REMOTE\\_IO\\_SERVER
- `87` - CANNOT\\_SEEK\\_THROUGH\\_FILE
- `88` - CANNOT\\_TRUNCATE\\_FILE
- `89` - UNKNOWN\\_COMPRESSION\\_METHOD
- `90` - EMPTY\\_LIST\\_OF\\_COLUMNS\\_PASSED
- `91` - SIZES\\_OF\\_MARKS\\_FILES\\_ARE\\_INCONSISTENT
- `92` - EMPTY\\_DATA\\_PASSED
- `93` - UNKNOWN\\_AGGREGATED\\_DATA\\_VARIANT
- `94` - CANNOT\\_MERGE\\_DIFFERENT\\_AGGREGATED\\_DATA\\_VARIANTS
- `95` - CANNOT\\_READ\\_FROM\\_SOCKET
- `96` - CANNOT\\_WRITE\\_TO\\_SOCKET
- `99` - UNKNOWN\\_PACKET\\_FROM\\_CLIENT
- `100` - UNKNOWN\\_PACKET\\_FROM\\_SERVER
- `101` - UNEXPECTED\\_PACKET\\_FROM\\_CLIENT
- `102` - UNEXPECTED\\_PACKET\\_FROM\\_SERVER
- `104` - TOO\\_SMALL\\_BUFFER\\_SIZE
- `107` - FILE\\_DOESNT\\_EXIST
- `108` - NO\\_DATA\\_TO\\_INSERT
- `109` - CANNOT\\_BLOCK\\_SIGNAL
- `110` - CANNOT\\_UNBLOCK\\_SIGNAL
- `111` - CANNOT\\_MANIPULATE\\_SIGSET
- `112` - CANNOT\\_WAIT\\_FOR\\_SIGNAL
- `113` - THERE\\_IS\\_NO\\_SESSION
- `114` - CANNOT\\_CLOCK\\_GETTIME
- `115` - UNKNOWN\\_SETTING
- `116` - THERE\\_IS\\_NO\\_DEFAULT\\_VALUE
- `117` - INCORRECT\\_DATA
- `119` - ENGINE\\_REQUIRED
- `120` - CANNOT\\_INSERT\\_VALUE\\_OF\\_DIFFERENT\\_SIZE\\_INTO\\_TUPLE
- `121` - UNSUPPORTED\\_JOIN\\_KEYS
- `122` - INCOMPATIBLE\\_COLUMNS
- `123` - UNKNOWN\\_TYPE\\_OF\\_AST\\_NODE
- `124` - INCORRECT\\_ELEMENT\\_OF\\_SET
- `125` - INCORRECT\\_RESULT\\_OF\\_SCALAR\\_SUBQUERY
- `127` - ILLEGAL\\_INDEX
- `128` - TOO\\_LARGE\\_ARRAY\\_SIZE
- `129` - FUNCTION\\_IS\\_SPECIAL
- `130` - CANNOT\\_READ\\_ARRAY\\_FROM\\_TEXT
- `131` - TOO\\_LARGE\\_STRING\\_SIZE
- `133` - AGGREGATE\\_FUNCTION\\_DOESNT\\_ALLOW\\_PARAMETERS
- `134` - PARAMETERS\\_TO\\_AGGREGATE\\_FUNCTIONS\\_MUST\\_BE\\_LITERALS
- `135` - ZERO\\_ARRAY\\_OR\\_TUPLE\\_INDEX
- `137` - UNKNOWN\\_ELEMENT\\_IN\\_CONFIG
- `138` - EXCESSIVE\\_ELEMENT\\_IN\\_CONFIG
- `139` - NO\\_ELEMENTS\\_IN\\_CONFIG
- `141` - SAMPLING\\_NOT\\_SUPPORTED
- `142` - NOT\\_FOUND\\_NODE
- `145` - UNKNOWN\\_OVERFLOW\\_MODE
- `152` - UNKNOWN\\_DIRECTION\\_OF\\_SORTING
- `153` - ILLEGAL\\_DIVISION
- `156` - DICTIONARIES\\_WAS\\_NOT\\_LOADED
- `158` - TOO\\_MANY\\_ROWS
- `159` - TIMEOUT\\_EXCEEDED
- `160` - TOO\\_SLOW
- `161` - TOO\\_MANY\\_COLUMNS
- `162` - TOO\\_DEEP\\_SUBQUERIES
- `164` - READONLY
- `165` - TOO\\_MANY\\_TEMPORARY\\_COLUMNS
- `166` - TOO\\_MANY\\_TEMPORARY\\_NON\\_CONST\\_COLUMNS
- `167` - TOO\\_DEEP\\_AST
- `168` - TOO\\_BIG\\_AST
- `169` - BAD\\_TYPE\\_OF\\_FIELD
- `170` - BAD\\_GET
- `172` - CANNOT\\_CREATE\\_DIRECTORY
- `173` - CANNOT\\_ALLOCATE\\_MEMORY
- `174` - CYCLIC\\_ALIASES
- `179` - MULTIPLE\\_EXPRESSIONS\\_FOR\\_ALIAS
- `180` - THERE\\_IS\\_NO\\_PROFILE
- `181` - ILLEGAL\\_FINAL
- `182` - ILLEGAL\\_PREWHERE
- `183` - UNEXPECTED\\_EXPRESSION
- `184` - ILLEGAL\\_AGGREGATION
- `186` - UNSUPPORTED\\_COLLATION\\_LOCALE
- `187` - COLLATION\\_COMPARISON\\_FAILED
- `190` - SIZES\\_OF\\_ARRAYS\\_DONT\\_MATCH
- `191` - SET\\_SIZE\\_LIMIT\\_EXCEEDED
- `192` - UNKNOWN\\_USER
- `193` - WRONG\\_PASSWORD
- `194` - REQUIRED\\_PASSWORD
- `195` - IP\\_ADDRESS\\_NOT\\_ALLOWED
- `196` - UNKNOWN\\_ADDRESS\\_PATTERN\\_TYPE
- `198` - DNS\\_ERROR
- `199` - UNKNOWN\\_QUOTA
- `201` - QUOTA\\_EXCEEDED
- `202` - TOO\\_MANY\\_SIMULTANEOUS\\_QUERIES
- `203` - NO\\_FREE\\_CONNECTION
- `204` - CANNOT\\_FSYNC
- `206` - ALIAS\\_REQUIRED
- `207` - AMBIGUOUS\\_IDENTIFIER
- `208` - EMPTY\\_NESTED\\_TABLE
- `209` - SOCKET\\_TIMEOUT
- `210` - NETWORK\\_ERROR
- `211` - EMPTY\\_QUERY
- `212` - UNKNOWN\\_LOAD\\_BALANCING
- `213` - UNKNOWN\\_TOTALS\\_MODE
- `214` - CANNOT\\_STATVFS
- `215` - NOT\\_AN\\_AGGREGATE
- `216` - QUERY\\_WITH\\_SAME\\_ID\\_IS\\_ALREADY\\_RUNNING
- `217` - CLIENT\\_HAS\\_CONNECTED\\_TO\\_WRONG\\_PORT
- `218` - TABLE\\_IS\\_DROPPED
- `219` - DATABASE\\_NOT\\_EMPTY
- `220` - DUPLICATE\\_INTERSERVER\\_IO\\_ENDPOINT
- `221` - NO\\_SUCH\\_INTERSERVER\\_IO\\_ENDPOINT
- `223` - UNEXPECTED\\_AST\\_STRUCTURE
- `224` - REPLICA\\_IS\\_ALREADY\\_ACTIVE
- `225` - NO\\_ZOOKEEPER
- `226` - NO\\_FILE\\_IN\\_DATA\\_PART
- `227` - UNEXPECTED\\_FILE\\_IN\\_DATA\\_PART
- `228` - BAD\\_SIZE\\_OF\\_FILE\\_IN\\_DATA\\_PART
- `229` - QUERY\\_IS\\_TOO\\_LARGE
- `230` - NOT\\_FOUND\\_EXPECTED\\_DATA\\_PART
- `231` - TOO\\_MANY\\_UNEXPECTED\\_DATA\\_PARTS
- `232` - NO\\_SUCH\\_DATA\\_PART
- `233` - BAD\\_DATA\\_PART\\_NAME
- `234` - NO\\_REPLICA\\_HAS\\_PART
- `235` - DUPLICATE\\_DATA\\_PART
- `236` - ABORTED
- `237` - NO\\_REPLICA\\_NAME\\_GIVEN
- `238` - FORMAT\\_VERSION\\_TOO\\_OLD
- `239` - CANNOT\\_MUNMAP
- `240` - CANNOT\\_MREMAP
- `241` - MEMORY\\_LIMIT\\_EXCEEDED
- `242` - TABLE\\_IS\\_READ\\_ONLY
- `243` - NOT\\_ENOUGH\\_SPACE
- `244` - UNEXPECTED\\_ZOOKEEPER\\_ERROR
- `246` - CORRUPTED\\_DATA
- `248` - INVALID\\_PARTITION\\_VALUE
- `251` - NO\\_SUCH\\_REPLICA
- `252` - TOO\\_MANY\\_PARTS
- `253` - REPLICA\\_ALREADY\\_EXISTS
- `254` - NO\\_ACTIVE\\_REPLICAS
- `255` - TOO\\_MANY\\_RETRIES\\_TO\\_FETCH\\_PARTS
- `256` - PARTITION\\_ALREADY\\_EXISTS
- `257` - PARTITION\\_DOESNT\\_EXIST
- `258` - UNION\\_ALL\\_RESULT\\_STRUCTURES\\_MISMATCH
- `260` - CLIENT\\_OUTPUT\\_FORMAT\\_SPECIFIED
- `261` - UNKNOWN\\_BLOCK\\_INFO\\_FIELD
- `262` - BAD\\_COLLATION
- `263` - CANNOT\\_COMPILE\\_CODE
- `264` - INCOMPATIBLE\\_TYPE\\_OF\\_JOIN
- `265` - NO\\_AVAILABLE\\_REPLICA
- `266` - MISMATCH\\_REPLICAS\\_DATA\\_SOURCES
- `269` - INFINITE\\_LOOP
- `270` - CANNOT\\_COMPRESS
- `271` - CANNOT\\_DECOMPRESS
- `272` - CANNOT\\_IO\\_SUBMIT
- `273` - CANNOT\\_IO\\_GETEVENTS
- `274` - AIO\\_READ\\_ERROR
- `275` - AIO\\_WRITE\\_ERROR
- `277` - INDEX\\_NOT\\_USED
- `279` - ALL\\_CONNECTION\\_TRIES\\_FAILED
- `280` - NO\\_AVAILABLE\\_DATA
- `281` - DICTIONARY\\_IS\\_EMPTY
- `282` - INCORRECT\\_INDEX
- `283` - UNKNOWN\\_DISTRIBUTED\\_PRODUCT\\_MODE
- `284` - WRONG\\_GLOBAL\\_SUBQUERY
- `285` - TOO\\_FEW\\_LIVE\\_REPLICAS
- `286` - UNSATISFIED\\_QUORUM\\_FOR\\_PREVIOUS\\_WRITE
- `287` - UNKNOWN\\_FORMAT\\_VERSION
- `288` - DISTRIBUTED\\_IN\\_JOIN\\_SUBQUERY\\_DENIED
- `289` - REPLICA\\_IS\\_NOT\\_IN\\_QUORUM
- `290` - LIMIT\\_EXCEEDED
- `291` - DATABASE\\_ACCESS\\_DENIED
- `293` - MONGODB\\_CANNOT\\_AUTHENTICATE
- `295` - RECEIVED\\_EMPTY\\_DATA
- `297` - SHARD\\_HAS\\_NO\\_CONNECTIONS
- `298` - CANNOT\\_PIPE
- `299` - CANNOT\\_FORK
- `300` - CANNOT\\_DLSYM
- `301` - CANNOT\\_CREATE\\_CHILD\\_PROCESS
- `302` - CHILD\\_WAS\\_NOT\\_EXITED\\_NORMALLY
- `303` - CANNOT\\_SELECT
- `304` - CANNOT\\_WAITPID
- `305` - TABLE\\_WAS\\_NOT\\_DROPPED
- `306` - TOO\\_DEEP\\_RECURSION
- `307` - TOO\\_MANY\\_BYTES
- `308` - UNEXPECTED\\_NODE\\_IN\\_ZOOKEEPER
- `309` - FUNCTION\\_CANNOT\\_HAVE\\_PARAMETERS
- `318` - INVALID\\_CONFIG\\_PARAMETER
- `319` - UNKNOWN\\_STATUS\\_OF\\_INSERT
- `321` - VALUE\\_IS\\_OUT\\_OF\\_RANGE\\_OF\\_DATA\\_TYPE
- `336` - UNKNOWN\\_DATABASE\\_ENGINE
- `341` - UNFINISHED
- `342` - METADATA\\_MISMATCH
- `344` - SUPPORT\\_IS\\_DISABLED
- `345` - TABLE\\_DIFFERS\\_TOO\\_MUCH
- `346` - CANNOT\\_CONVERT\\_CHARSET
- `347` - CANNOT\\_LOAD\\_CONFIG
- `349` - CANNOT\\_INSERT\\_NULL\\_IN\\_ORDINARY\\_COLUMN
- `352` - AMBIGUOUS\\_COLUMN\\_NAME
- `353` - INDEX\\_OF\\_POSITIONAL\\_ARGUMENT\\_IS\\_OUT\\_OF\\_RANGE
- `354` - ZLIB\\_INFLATE\\_FAILED
- `355` - ZLIB\\_DEFLATE\\_FAILED
- `358` - INTO\\_OUTFILE\\_NOT\\_ALLOWED
- `359` - TABLE\\_SIZE\\_EXCEEDS\\_MAX\\_DROP\\_SIZE\\_LIMIT
- `360` - CANNOT\\_CREATE\\_CHARSET\\_CONVERTER
- `361` - SEEK\\_POSITION\\_OUT\\_OF\\_BOUND
- `362` - CURRENT\\_WRITE\\_BUFFER\\_IS\\_EXHAUSTED
- `363` - CANNOT\\_CREATE\\_IO\\_BUFFER
- `364` - RECEIVED\\_ERROR\\_TOO\\_MANY\\_REQUESTS
- `366` - SIZES\\_OF\\_NESTED\\_COLUMNS\\_ARE\\_INCONSISTENT
- `369` - ALL\\_REPLICAS\\_ARE\\_STALE
- `370` - DATA\\_TYPE\\_CANNOT\\_BE\\_USED\\_IN\\_TABLES
- `371` - INCONSISTENT\\_CLUSTER\\_DEFINITION
- `372` - SESSION\\_NOT\\_FOUND
- `373` - SESSION\\_IS\\_LOCKED
- `374` - INVALID\\_SESSION\\_TIMEOUT
- `375` - CANNOT\\_DLOPEN
- `376` - CANNOT\\_PARSE\\_UUID
- `377` - ILLEGAL\\_SYNTAX\\_FOR\\_DATA\\_TYPE
- `378` - DATA\\_TYPE\\_CANNOT\\_HAVE\\_ARGUMENTS
- `380` - CANNOT\\_KILL
- `381` - HTTP\\_LENGTH\\_REQUIRED
- `382` - CANNOT\\_LOAD\\_CATBOOST\\_MODEL
- `383` - CANNOT\\_APPLY\\_CATBOOST\\_MODEL
- `384` - PART\\_IS\\_TEMPORARILY\\_LOCKED
- `385` - MULTIPLE\\_STREAMS\\_REQUIRED
- `386` - NO\\_COMMON\\_TYPE
- `387` - DICTIONARY\\_ALREADY\\_EXISTS
- `388` - CANNOT\\_ASSIGN\\_OPTIMIZE
- `389` - INSERT\\_WAS\\_DEDUPLICATED
- `390` - CANNOT\\_GET\\_CREATE\\_TABLE\\_QUERY
- `391` - EXTERNAL\\_LIBRARY\\_ERROR
- `392` - QUERY\\_IS\\_PROHIBITED
- `393` - THERE\\_IS\\_NO\\_QUERY
- `394` - QUERY\\_WAS\\_CANCELLED
- `395` - FUNCTION\\_THROW\\_IF\\_VALUE\\_IS\\_NON\\_ZERO
- `396` - TOO\\_MANY\\_ROWS\\_OR\\_BYTES
- `397` - QUERY\\_IS\\_NOT\\_SUPPORTED\\_IN\\_MATERIALIZED\\_VIEW
- `398` - UNKNOWN\\_MUTATION\\_COMMAND
- `399` - FORMAT\\_IS\\_NOT\\_SUITABLE\\_FOR\\_OUTPUT
- `400` - CANNOT\\_STAT
- `401` - FEATURE\\_IS\\_NOT\\_ENABLED\\_AT\\_BUILD\\_TIME
- `402` - CANNOT\\_IOSETUP
- `403` - INVALID\\_JOIN\\_ON\\_EXPRESSION
- `404` - BAD\\_ODBC\\_CONNECTION\\_STRING
- `406` - TOP\\_AND\\_LIMIT\\_TOGETHER
- `407` - DECIMAL\\_OVERFLOW
- `408` - BAD\\_REQUEST\\_PARAMETER
- `410` - EXTERNAL\\_SERVER\\_IS\\_NOT\\_RESPONDING
- `411` - PTHREAD\\_ERROR
- `412` - NETLINK\\_ERROR
- `413` - CANNOT\\_SET\\_SIGNAL\\_HANDLER
- `415` - ALL\\_REPLICAS\\_LOST
- `416` - REPLICA\\_STATUS\\_CHANGED
- `417` - EXPECTED\\_ALL\\_OR\\_ANY
- `418` - UNKNOWN\\_JOIN
- `419` - MULTIPLE\\_ASSIGNMENTS\\_TO\\_COLUMN
- `420` - CANNOT\\_UPDATE\\_COLUMN
- `421` - CANNOT\\_ADD\\_DIFFERENT\\_AGGREGATE\\_STATES
- `422` - UNSUPPORTED\\_URI\\_SCHEME
- `423` - CANNOT\\_GETTIMEOFDAY
- `424` - CANNOT\\_LINK
- `425` - SYSTEM\\_ERROR
- `427` - CANNOT\\_COMPILE\\_REGEXP
- `429` - FAILED\\_TO\\_GETPWUID
- `430` - MISMATCHING\\_USERS\\_FOR\\_PROCESS\\_AND\\_DATA
- `431` - ILLEGAL\\_SYNTAX\\_FOR\\_CODEC\\_TYPE
- `432` - UNKNOWN\\_CODEC
- `433` - ILLEGAL\\_CODEC\\_PARAMETER
- `434` - CANNOT\\_PARSE\\_PROTOBUF\\_SCHEMA
- `435` - NO\\_COLUMN\\_SERIALIZED\\_TO\\_REQUIRED\\_PROTOBUF\\_FIELD
- `436` - PROTOBUF\\_BAD\\_CAST
- `437` - PROTOBUF\\_FIELD\\_NOT\\_REPEATED
- `438` - DATA\\_TYPE\\_CANNOT\\_BE\\_PROMOTED
- `439` - CANNOT\\_SCHEDULE\\_TASK
- `440` - INVALID\\_LIMIT\\_EXPRESSION
- `441` - CANNOT\\_PARSE\\_DOMAIN\\_VALUE\\_FROM\\_STRING
- `442` - BAD\\_DATABASE\\_FOR\\_TEMPORARY\\_TABLE
- `443` - NO\\_COLUMNS\\_SERIALIZED\\_TO\\_PROTOBUF\\_FIELDS
- `444` - UNKNOWN\\_PROTOBUF\\_FORMAT
- `445` - CANNOT\\_MPROTECT
- `446` - FUNCTION\\_NOT\\_ALLOWED
- `447` - HYPERSCAN\\_CANNOT\\_SCAN\\_TEXT
- `448` - BROTLI\\_READ\\_FAILED
- `449` - BROTLI\\_WRITE\\_FAILED
- `450` - BAD\\_TTL\\_EXPRESSION
- `451` - BAD\\_TTL\\_FILE
- `452` - SETTING\\_CONSTRAINT\\_VIOLATION
- `453` - MYSQL\\_CLIENT\\_INSUFFICIENT\\_CAPABILITIES
- `454` - OPENSSL\\_ERROR
- `455` - SUSPICIOUS\\_TYPE\\_FOR\\_LOW\\_CARDINALITY
- `456` - UNKNOWN\\_QUERY\\_PARAMETER
- `457` - BAD\\_QUERY\\_PARAMETER
- `458` - CANNOT\\_UNLINK
- `459` - CANNOT\\_SET\\_THREAD\\_PRIORITY
- `460` - CANNOT\\_CREATE\\_TIMER
- `461` - CANNOT\\_SET\\_TIMER\\_PERIOD
- `463` - CANNOT\\_FCNTL
- `464` - CANNOT\\_PARSE\\_ELF
- `465` - CANNOT\\_PARSE\\_DWARF
- `466` - INSECURE\\_PATH
- `467` - CANNOT\\_PARSE\\_BOOL
- `468` - CANNOT\\_PTHREAD\\_ATTR
- `469` - VIOLATED\\_CONSTRAINT
- `470` - QUERY\\_IS\\_NOT\\_SUPPORTED\\_IN\\_LIVE\\_VIEW
- `471` - INVALID\\_SETTING\\_VALUE
- `472` - READONLY\\_SETTING
- `473` - DEADLOCK\\_AVOIDED
- `474` - INVALID\\_TEMPLATE\\_FORMAT
- `475` - INVALID\\_WITH\\_FILL\\_EXPRESSION
- `476` - WITH\\_TIES\\_WITHOUT\\_ORDER\\_BY
- `477` - INVALID\\_USAGE\\_OF\\_INPUT
- `478` - UNKNOWN\\_POLICY
- `479` - UNKNOWN\\_DISK
- `480` - UNKNOWN\\_PROTOCOL
- `481` - PATH\\_ACCESS\\_DENIED
- `482` - DICTIONARY\\_ACCESS\\_DENIED
- `483` - TOO\\_MANY\\_REDIRECTS
- `484` - INTERNAL\\_REDIS\\_ERROR
- `487` - CANNOT\\_GET\\_CREATE\\_DICTIONARY\\_QUERY
- `489` - INCORRECT\\_DICTIONARY\\_DEFINITION
- `490` - CANNOT\\_FORMAT\\_DATETIME
- `491` - UNACCEPTABLE\\_URL
- `492` - ACCESS\\_ENTITY\\_NOT\\_FOUND
- `493` - ACCESS\\_ENTITY\\_ALREADY\\_EXISTS
- `495` - ACCESS\\_STORAGE\\_READONLY
- `496` - QUOTA\\_REQUIRES\\_CLIENT\\_KEY
- `497` - ACCESS\\_DENIED
- `498` - LIMIT\\_BY\\_WITH\\_TIES\\_IS\\_NOT\\_SUPPORTED
- `499` - S3\\_ERROR
- `500` - AZURE\\_BLOB\\_STORAGE\\_ERROR
- `501` - CANNOT\\_CREATE\\_DATABASE
- `502` - CANNOT\\_SIGQUEUE
- `503` - AGGREGATE\\_FUNCTION\\_THROW
- `504` - FILE\\_ALREADY\\_EXISTS
- `507` - UNABLE\\_TO\\_SKIP\\_UNUSED\\_SHARDS
- `508` - UNKNOWN\\_ACCESS\\_TYPE
- `509` - INVALID\\_GRANT
- `510` - CACHE\\_DICTIONARY\\_UPDATE\\_FAIL
- `511` - UNKNOWN\\_ROLE
- `512` - SET\\_NON\\_GRANTED\\_ROLE
- `513` - UNKNOWN\\_PART\\_TYPE
- `514` - ACCESS\\_STORAGE\\_FOR\\_INSERTION\\_NOT\\_FOUND
- `515` - INCORRECT\\_ACCESS\\_ENTITY\\_DEFINITION
- `516` - AUTHENTICATION\\_FAILED
- `517` - CANNOT\\_ASSIGN\\_ALTER
- `518` - CANNOT\\_COMMIT\\_OFFSET
- `519` - NO\\_REMOTE\\_SHARD\\_AVAILABLE
- `520` - CANNOT\\_DETACH\\_DICTIONARY\\_AS\\_TABLE
- `521` - ATOMIC\\_RENAME\\_FAIL
- `523` - UNKNOWN\\_ROW\\_POLICY
- `524` - ALTER\\_OF\\_COLUMN\\_IS\\_FORBIDDEN
- `525` - INCORRECT\\_DISK\\_INDEX
- `527` - NO\\_SUITABLE\\_FUNCTION\\_IMPLEMENTATION
- `528` - CASSANDRA\\_INTERNAL\\_ERROR
- `529` - NOT\\_A\\_LEADER
- `530` - CANNOT\\_CONNECT\\_RABBITMQ
- `531` - CANNOT\\_FSTAT
- `532` - LDAP\\_ERROR
- `535` - UNKNOWN\\_RAID\\_TYPE
- `536` - CANNOT\\_RESTORE\\_FROM\\_FIELD\\_DUMP
- `537` - ILLEGAL\\_MYSQL\\_VARIABLE
- `538` - MYSQL\\_SYNTAX\\_ERROR
- `539` - CANNOT\\_BIND\\_RABBITMQ\\_EXCHANGE
- `540` - CANNOT\\_DECLARE\\_RABBITMQ\\_EXCHANGE
- `541` - CANNOT\\_CREATE\\_RABBITMQ\\_QUEUE\\_BINDING
- `542` - CANNOT\\_REMOVE\\_RABBITMQ\\_EXCHANGE
- `543` - UNKNOWN\\_MYSQL\\_DATATYPES\\_SUPPORT\\_LEVEL
- `544` - ROW\\_AND\\_ROWS\\_TOGETHER
- `545` - FIRST\\_AND\\_NEXT\\_TOGETHER
- `546` - NO\\_ROW\\_DELIMITER
- `547` - INVALID\\_RAID\\_TYPE
- `548` - UNKNOWN\\_VOLUME
- `549` - DATA\\_TYPE\\_CANNOT\\_BE\\_USED\\_IN\\_KEY
- `552` - UNRECOGNIZED\\_ARGUMENTS
- `553` - LZMA\\_STREAM\\_ENCODER\\_FAILED
- `554` - LZMA\\_STREAM\\_DECODER\\_FAILED
- `555` - ROCKSDB\\_ERROR
- `556` - SYNC\\_MYSQL\\_USER\\_ACCESS\\_ERROR
- `557` - UNKNOWN\\_UNION
- `558` - EXPECTED\\_ALL\\_OR\\_DISTINCT
- `559` - INVALID\\_GRPC\\_QUERY\\_INFO
- `560` - ZSTD\\_ENCODER\\_FAILED
- `561` - ZSTD\\_DECODER\\_FAILED
- `562` - TLD\\_LIST\\_NOT\\_FOUND
- `563` - CANNOT\\_READ\\_MAP\\_FROM\\_TEXT
- `564` - INTERSERVER\\_SCHEME\\_DOESNT\\_MATCH
- `565` - TOO\\_MANY\\_PARTITIONS
- `566` - CANNOT\\_RMDIR
- `567` - DUPLICATED\\_PART\\_UUIDS
- `568` - RAFT\\_ERROR
- `569` - MULTIPLE\\_COLUMNS\\_SERIALIZED\\_TO\\_SAME\\_PROTOBUF\\_FIELD
- `570` - DATA\\_TYPE\\_INCOMPATIBLE\\_WITH\\_PROTOBUF\\_FIELD
- `571` - DATABASE\\_REPLICATION\\_FAILED
- `572` - TOO\\_MANY\\_QUERY\\_PLAN\\_OPTIMIZATIONS
- `573` - EPOLL\\_ERROR
- `574` - DISTRIBUTED\\_TOO\\_MANY\\_PENDING\\_BYTES
- `575` - UNKNOWN\\_SNAPSHOT
- `576` - KERBEROS\\_ERROR
- `577` - INVALID\\_SHARD\\_ID
- `578` - INVALID\\_FORMAT\\_INSERT\\_QUERY\\_WITH\\_DATA
- `579` - INCORRECT\\_PART\\_TYPE
- `580` - CANNOT\\_SET\\_ROUNDING\\_MODE
- `581` - TOO\\_LARGE\\_DISTRIBUTED\\_DEPTH
- `582` - NO\\_SUCH\\_PROJECTION\\_IN\\_TABLE
- `583` - ILLEGAL\\_PROJECTION
- `584` - PROJECTION\\_NOT\\_USED
- `585` - CANNOT\\_PARSE\\_YAML
- `586` - CANNOT\\_CREATE\\_FILE
- `587` - CONCURRENT\\_ACCESS\\_NOT\\_SUPPORTED
- `588` - DISTRIBUTED\\_BROKEN\\_BATCH\\_INFO
- `589` - DISTRIBUTED\\_BROKEN\\_BATCH\\_FILES
- `590` - CANNOT\\_SYSCONF
- `591` - SQLITE\\_ENGINE\\_ERROR
- `592` - DATA\\_ENCRYPTION\\_ERROR
- `593` - ZERO\\_COPY\\_REPLICATION\\_ERROR
- `594` - BZIP2\\_STREAM\\_DECODER\\_FAILED
- `595` - BZIP2\\_STREAM\\_ENCODER\\_FAILED
- `596` - INTERSECT\\_OR\\_EXCEPT\\_RESULT\\_STRUCTURES\\_MISMATCH
- `597` - NO\\_SUCH\\_ERROR\\_CODE
- `598` - BACKUP\\_ALREADY\\_EXISTS
- `599` - BACKUP\\_NOT\\_FOUND
- `600` - BACKUP\\_VERSION\\_NOT\\_SUPPORTED
- `601` - BACKUP\\_DAMAGED
- `602` - NO\\_BASE\\_BACKUP
- `603` - WRONG\\_BASE\\_BACKUP
- `604` - BACKUP\\_ENTRY\\_ALREADY\\_EXISTS
- `605` - BACKUP\\_ENTRY\\_NOT\\_FOUND
- `606` - BACKUP\\_IS\\_EMPTY
- `607` - CANNOT\\_RESTORE\\_DATABASE
- `608` - CANNOT\\_RESTORE\\_TABLE
- `609` - FUNCTION\\_ALREADY\\_EXISTS
- `610` - CANNOT\\_DROP\\_FUNCTION
- `611` - CANNOT\\_CREATE\\_RECURSIVE\\_FUNCTION
- `614` - POSTGRESQL\\_CONNECTION\\_FAILURE
- `615` - CANNOT\\_ADVISE
- `616` - UNKNOWN\\_READ\\_METHOD
- `617` - LZ4\\_ENCODER\\_FAILED
- `618` - LZ4\\_DECODER\\_FAILED
- `619` - POSTGRESQL\\_REPLICATION\\_INTERNAL\\_ERROR
- `620` - QUERY\\_NOT\\_ALLOWED
- `621` - CANNOT\\_NORMALIZE\\_STRING
- `622` - CANNOT\\_PARSE\\_CAPN\\_PROTO\\_SCHEMA
- `623` - CAPN\\_PROTO\\_BAD\\_CAST
- `624` - BAD\\_FILE\\_TYPE
- `625` - IO\\_SETUP\\_ERROR
- `626` - CANNOT\\_SKIP\\_UNKNOWN\\_FIELD
- `627` - BACKUP\\_ENGINE\\_NOT\\_FOUND
- `628` - OFFSET\\_FETCH\\_WITHOUT\\_ORDER\\_BY
- `629` - HTTP\\_RANGE\\_NOT\\_SATISFIABLE
- `630` - HAVE\\_DEPENDENT\\_OBJECTS
- `631` - UNKNOWN\\_FILE\\_SIZE
- `632` - UNEXPECTED\\_DATA\\_AFTER\\_PARSED\\_VALUE
- `633` - QUERY\\_IS\\_NOT\\_SUPPORTED\\_IN\\_WINDOW\\_VIEW
- `634` - MONGODB\\_ERROR
- `635` - CANNOT\\_POLL
- `636` - CANNOT\\_EXTRACT\\_TABLE\\_STRUCTURE
- `637` - INVALID\\_TABLE\\_OVERRIDE
- `638` - SNAPPY\\_UNCOMPRESS\\_FAILED
- `639` - SNAPPY\\_COMPRESS\\_FAILED
- `640` - NO\\_HIVEMETASTORE
- `641` - CANNOT\\_APPEND\\_TO\\_FILE
- `642` - CANNOT\\_PACK\\_ARCHIVE
- `643` - CANNOT\\_UNPACK\\_ARCHIVE
- `645` - NUMBER\\_OF\\_DIMENSIONS\\_MISMATCHED
- `647` - CANNOT\\_BACKUP\\_TABLE
- `648` - WRONG\\_DDL\\_RENAMING\\_SETTINGS
- `649` - INVALID\\_TRANSACTION
- `650` - SERIALIZATION\\_ERROR
- `651` - CAPN\\_PROTO\\_BAD\\_TYPE
- `652` - ONLY\\_NULLS\\_WHILE\\_READING\\_SCHEMA
- `653` - CANNOT\\_PARSE\\_BACKUP\\_SETTINGS
- `654` - WRONG\\_BACKUP\\_SETTINGS
- `655` - FAILED\\_TO\\_SYNC\\_BACKUP\\_OR\\_RESTORE
- `659` - UNKNOWN\\_STATUS\\_OF\\_TRANSACTION
- `660` - HDFS\\_ERROR
- `661` - CANNOT\\_SEND\\_SIGNAL
- `662` - FS\\_METADATA\\_ERROR
- `663` - INCONSISTENT\\_METADATA\\_FOR\\_BACKUP
- `664` - ACCESS\\_STORAGE\\_DOESNT\\_ALLOW\\_BACKUP
- `665` - CANNOT\\_CONNECT\\_NATS
- `667` - NOT\\_INITIALIZED
- `668` - INVALID\\_STATE
- `669` - NAMED\\_COLLECTION\\_DOESNT\\_EXIST
- `670` - NAMED\\_COLLECTION\\_ALREADY\\_EXISTS
- `671` - NAMED\\_COLLECTION\\_IS\\_IMMUTABLE
- `672` - INVALID\\_SCHEDULER\\_NODE
- `673` - RESOURCE\\_ACCESS\\_DENIED
- `674` - RESOURCE\\_NOT\\_FOUND
- `675` - CANNOT\\_PARSE\\_IPV4
- `676` - CANNOT\\_PARSE\\_IPV6
- `677` - THREAD\\_WAS\\_CANCELED
- `678` - IO\\_URING\\_INIT\\_FAILED
- `679` - IO\\_URING\\_SUBMIT\\_ERROR
- `690` - MIXED\\_ACCESS\\_PARAMETER\\_TYPES
- `691` - UNKNOWN\\_ELEMENT\\_OF\\_ENUM
- `692` - TOO\\_MANY\\_MUTATIONS
- `693` - AWS\\_ERROR
- `694` - ASYNC\\_LOAD\\_CYCLE
- `695` - ASYNC\\_LOAD\\_FAILED
- `696` - ASYNC\\_LOAD\\_CANCELED
- `697` - CANNOT\\_RESTORE\\_TO\\_NONENCRYPTED\\_DISK
- `698` - INVALID\\_REDIS\\_STORAGE\\_TYPE
- `699` - INVALID\\_REDIS\\_TABLE\\_STRUCTURE
- `700` - USER\\_SESSION\\_LIMIT\\_EXCEEDED
- `701` - CLUSTER\\_DOESNT\\_EXIST
- `702` - CLIENT\\_INFO\\_DOES\\_NOT\\_MATCH
- `703` - INVALID\\_IDENTIFIER
- `704` - QUERY\\_CACHE\\_USED\\_WITH\\_NONDETERMINISTIC\\_FUNCTIONS
- `705` - TABLE\\_NOT\\_EMPTY
- `706` - LIBSSH\\_ERROR
- `707` - GCP\\_ERROR
- `999` - KEEPER\\_EXCEPTION
- `1000` - POCO\\_EXCEPTION
- `1001` - STD\\_EXCEPTION
- `1002` - UNKNOWN\\_EXCEPTION
"""
@enum ErrorCodes begin
    OK = 0
    UNSUPPORTED_METHOD = 1
    UNSUPPORTED_PARAMETER = 2
    UNEXPECTED_END_OF_FILE = 3
    EXPECTED_END_OF_FILE = 4
    CANNOT_PARSE_TEXT = 6
    INCORRECT_NUMBER_OF_COLUMNS = 7
    THERE_IS_NO_COLUMN = 8
    SIZES_OF_COLUMNS_DOESNT_MATCH = 9
    NOT_FOUND_COLUMN_IN_BLOCK = 10
    POSITION_OUT_OF_BOUND = 11
    PARAMETER_OUT_OF_BOUND = 12
    SIZES_OF_COLUMNS_IN_TUPLE_DOESNT_MATCH = 13
    DUPLICATE_COLUMN = 15
    NO_SUCH_COLUMN_IN_TABLE = 16
    SIZE_OF_FIXED_STRING_DOESNT_MATCH = 19
    NUMBER_OF_COLUMNS_DOESNT_MATCH = 20
    CANNOT_READ_FROM_ISTREAM = 23
    CANNOT_WRITE_TO_OSTREAM = 24
    CANNOT_PARSE_ESCAPE_SEQUENCE = 25
    CANNOT_PARSE_QUOTED_STRING = 26
    CANNOT_PARSE_INPUT_ASSERTION_FAILED = 27
    CANNOT_PRINT_FLOAT_OR_DOUBLE_NUMBER = 28
    ATTEMPT_TO_READ_AFTER_EOF = 32
    CANNOT_READ_ALL_DATA = 33
    TOO_MANY_ARGUMENTS_FOR_FUNCTION = 34
    TOO_FEW_ARGUMENTS_FOR_FUNCTION = 35
    BAD_ARGUMENTS = 36
    UNKNOWN_ELEMENT_IN_AST = 37
    CANNOT_PARSE_DATE = 38
    TOO_LARGE_SIZE_COMPRESSED = 39
    CHECKSUM_DOESNT_MATCH = 40
    CANNOT_PARSE_DATETIME = 41
    NUMBER_OF_ARGUMENTS_DOESNT_MATCH = 42
    ILLEGAL_TYPE_OF_ARGUMENT = 43
    ILLEGAL_COLUMN = 44
    UNKNOWN_FUNCTION = 46
    UNKNOWN_IDENTIFIER = 47
    NOT_IMPLEMENTED = 48
    LOGICAL_ERROR = 49
    UNKNOWN_TYPE = 50
    EMPTY_LIST_OF_COLUMNS_QUERIED = 51
    COLUMN_QUERIED_MORE_THAN_ONCE = 52
    TYPE_MISMATCH = 53
    STORAGE_REQUIRES_PARAMETER = 55
    UNKNOWN_STORAGE = 56
    TABLE_ALREADY_EXISTS = 57
    TABLE_METADATA_ALREADY_EXISTS = 58
    ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER = 59
    UNKNOWN_TABLE = 60
    SYNTAX_ERROR = 62
    UNKNOWN_AGGREGATE_FUNCTION = 63
    CANNOT_GET_SIZE_OF_FIELD = 68
    ARGUMENT_OUT_OF_BOUND = 69
    CANNOT_CONVERT_TYPE = 70
    CANNOT_WRITE_AFTER_END_OF_BUFFER = 71
    CANNOT_PARSE_NUMBER = 72
    UNKNOWN_FORMAT = 73
    CANNOT_READ_FROM_FILE_DESCRIPTOR = 74
    CANNOT_WRITE_TO_FILE_DESCRIPTOR = 75
    CANNOT_OPEN_FILE = 76
    CANNOT_CLOSE_FILE = 77
    UNKNOWN_TYPE_OF_QUERY = 78
    INCORRECT_FILE_NAME = 79
    INCORRECT_QUERY = 80
    UNKNOWN_DATABASE = 81
    DATABASE_ALREADY_EXISTS = 82
    DIRECTORY_DOESNT_EXIST = 83
    DIRECTORY_ALREADY_EXISTS = 84
    FORMAT_IS_NOT_SUITABLE_FOR_INPUT = 85
    RECEIVED_ERROR_FROM_REMOTE_IO_SERVER = 86
    CANNOT_SEEK_THROUGH_FILE = 87
    CANNOT_TRUNCATE_FILE = 88
    UNKNOWN_COMPRESSION_METHOD = 89
    EMPTY_LIST_OF_COLUMNS_PASSED = 90
    SIZES_OF_MARKS_FILES_ARE_INCONSISTENT = 91
    EMPTY_DATA_PASSED = 92
    UNKNOWN_AGGREGATED_DATA_VARIANT = 93
    CANNOT_MERGE_DIFFERENT_AGGREGATED_DATA_VARIANTS = 94
    CANNOT_READ_FROM_SOCKET = 95
    CANNOT_WRITE_TO_SOCKET = 96
    UNKNOWN_PACKET_FROM_CLIENT = 99
    UNKNOWN_PACKET_FROM_SERVER = 100
    UNEXPECTED_PACKET_FROM_CLIENT = 101
    UNEXPECTED_PACKET_FROM_SERVER = 102
    TOO_SMALL_BUFFER_SIZE = 104
    FILE_DOESNT_EXIST = 107
    NO_DATA_TO_INSERT = 108
    CANNOT_BLOCK_SIGNAL = 109
    CANNOT_UNBLOCK_SIGNAL = 110
    CANNOT_MANIPULATE_SIGSET = 111
    CANNOT_WAIT_FOR_SIGNAL = 112
    THERE_IS_NO_SESSION = 113
    CANNOT_CLOCK_GETTIME = 114
    UNKNOWN_SETTING = 115
    THERE_IS_NO_DEFAULT_VALUE = 116
    INCORRECT_DATA = 117
    ENGINE_REQUIRED = 119
    CANNOT_INSERT_VALUE_OF_DIFFERENT_SIZE_INTO_TUPLE = 120
    UNSUPPORTED_JOIN_KEYS = 121
    INCOMPATIBLE_COLUMNS = 122
    UNKNOWN_TYPE_OF_AST_NODE = 123
    INCORRECT_ELEMENT_OF_SET = 124
    INCORRECT_RESULT_OF_SCALAR_SUBQUERY = 125
    ILLEGAL_INDEX = 127
    TOO_LARGE_ARRAY_SIZE = 128
    FUNCTION_IS_SPECIAL = 129
    CANNOT_READ_ARRAY_FROM_TEXT = 130
    TOO_LARGE_STRING_SIZE = 131
    AGGREGATE_FUNCTION_DOESNT_ALLOW_PARAMETERS = 133
    PARAMETERS_TO_AGGREGATE_FUNCTIONS_MUST_BE_LITERALS = 134
    ZERO_ARRAY_OR_TUPLE_INDEX = 135
    UNKNOWN_ELEMENT_IN_CONFIG = 137
    EXCESSIVE_ELEMENT_IN_CONFIG = 138
    NO_ELEMENTS_IN_CONFIG = 139
    SAMPLING_NOT_SUPPORTED = 141
    NOT_FOUND_NODE = 142
    UNKNOWN_OVERFLOW_MODE = 145
    UNKNOWN_DIRECTION_OF_SORTING = 152
    ILLEGAL_DIVISION = 153
    DICTIONARIES_WAS_NOT_LOADED = 156
    TOO_MANY_ROWS = 158
    TIMEOUT_EXCEEDED = 159
    TOO_SLOW = 160
    TOO_MANY_COLUMNS = 161
    TOO_DEEP_SUBQUERIES = 162
    READONLY = 164
    TOO_MANY_TEMPORARY_COLUMNS = 165
    TOO_MANY_TEMPORARY_NON_CONST_COLUMNS = 166
    TOO_DEEP_AST = 167
    TOO_BIG_AST = 168
    BAD_TYPE_OF_FIELD = 169
    BAD_GET = 170
    CANNOT_CREATE_DIRECTORY = 172
    CANNOT_ALLOCATE_MEMORY = 173
    CYCLIC_ALIASES = 174
    MULTIPLE_EXPRESSIONS_FOR_ALIAS = 179
    THERE_IS_NO_PROFILE = 180
    ILLEGAL_FINAL = 181
    ILLEGAL_PREWHERE = 182
    UNEXPECTED_EXPRESSION = 183
    ILLEGAL_AGGREGATION = 184
    UNSUPPORTED_COLLATION_LOCALE = 186
    COLLATION_COMPARISON_FAILED = 187
    SIZES_OF_ARRAYS_DONT_MATCH = 190
    SET_SIZE_LIMIT_EXCEEDED = 191
    UNKNOWN_USER = 192
    WRONG_PASSWORD = 193
    REQUIRED_PASSWORD = 194
    IP_ADDRESS_NOT_ALLOWED = 195
    UNKNOWN_ADDRESS_PATTERN_TYPE = 196
    DNS_ERROR = 198
    UNKNOWN_QUOTA = 199
    QUOTA_EXCEEDED = 201
    TOO_MANY_SIMULTANEOUS_QUERIES = 202
    NO_FREE_CONNECTION = 203
    CANNOT_FSYNC = 204
    ALIAS_REQUIRED = 206
    AMBIGUOUS_IDENTIFIER = 207
    EMPTY_NESTED_TABLE = 208
    SOCKET_TIMEOUT = 209
    NETWORK_ERROR = 210
    EMPTY_QUERY = 211
    UNKNOWN_LOAD_BALANCING = 212
    UNKNOWN_TOTALS_MODE = 213
    CANNOT_STATVFS = 214
    NOT_AN_AGGREGATE = 215
    QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING = 216
    CLIENT_HAS_CONNECTED_TO_WRONG_PORT = 217
    TABLE_IS_DROPPED = 218
    DATABASE_NOT_EMPTY = 219
    DUPLICATE_INTERSERVER_IO_ENDPOINT = 220
    NO_SUCH_INTERSERVER_IO_ENDPOINT = 221
    UNEXPECTED_AST_STRUCTURE = 223
    REPLICA_IS_ALREADY_ACTIVE = 224
    NO_ZOOKEEPER = 225
    NO_FILE_IN_DATA_PART = 226
    UNEXPECTED_FILE_IN_DATA_PART = 227
    BAD_SIZE_OF_FILE_IN_DATA_PART = 228
    QUERY_IS_TOO_LARGE = 229
    NOT_FOUND_EXPECTED_DATA_PART = 230
    TOO_MANY_UNEXPECTED_DATA_PARTS = 231
    NO_SUCH_DATA_PART = 232
    BAD_DATA_PART_NAME = 233
    NO_REPLICA_HAS_PART = 234
    DUPLICATE_DATA_PART = 235
    ABORTED = 236
    NO_REPLICA_NAME_GIVEN = 237
    FORMAT_VERSION_TOO_OLD = 238
    CANNOT_MUNMAP = 239
    CANNOT_MREMAP = 240
    MEMORY_LIMIT_EXCEEDED = 241
    TABLE_IS_READ_ONLY = 242
    NOT_ENOUGH_SPACE = 243
    UNEXPECTED_ZOOKEEPER_ERROR = 244
    CORRUPTED_DATA = 246
    INVALID_PARTITION_VALUE = 248
    NO_SUCH_REPLICA = 251
    TOO_MANY_PARTS = 252
    REPLICA_ALREADY_EXISTS = 253
    NO_ACTIVE_REPLICAS = 254
    TOO_MANY_RETRIES_TO_FETCH_PARTS = 255
    PARTITION_ALREADY_EXISTS = 256
    PARTITION_DOESNT_EXIST = 257
    UNION_ALL_RESULT_STRUCTURES_MISMATCH = 258
    CLIENT_OUTPUT_FORMAT_SPECIFIED = 260
    UNKNOWN_BLOCK_INFO_FIELD = 261
    BAD_COLLATION = 262
    CANNOT_COMPILE_CODE = 263
    INCOMPATIBLE_TYPE_OF_JOIN = 264
    NO_AVAILABLE_REPLICA = 265
    MISMATCH_REPLICAS_DATA_SOURCES = 266
    INFINITE_LOOP = 269
    CANNOT_COMPRESS = 270
    CANNOT_DECOMPRESS = 271
    CANNOT_IO_SUBMIT = 272
    CANNOT_IO_GETEVENTS = 273
    AIO_READ_ERROR = 274
    AIO_WRITE_ERROR = 275
    INDEX_NOT_USED = 277
    ALL_CONNECTION_TRIES_FAILED = 279
    NO_AVAILABLE_DATA = 280
    DICTIONARY_IS_EMPTY = 281
    INCORRECT_INDEX = 282
    UNKNOWN_DISTRIBUTED_PRODUCT_MODE = 283
    WRONG_GLOBAL_SUBQUERY = 284
    TOO_FEW_LIVE_REPLICAS = 285
    UNSATISFIED_QUORUM_FOR_PREVIOUS_WRITE = 286
    UNKNOWN_FORMAT_VERSION = 287
    DISTRIBUTED_IN_JOIN_SUBQUERY_DENIED = 288
    REPLICA_IS_NOT_IN_QUORUM = 289
    LIMIT_EXCEEDED = 290
    DATABASE_ACCESS_DENIED = 291
    MONGODB_CANNOT_AUTHENTICATE = 293
    RECEIVED_EMPTY_DATA = 295
    SHARD_HAS_NO_CONNECTIONS = 297
    CANNOT_PIPE = 298
    CANNOT_FORK = 299
    CANNOT_DLSYM = 300
    CANNOT_CREATE_CHILD_PROCESS = 301
    CHILD_WAS_NOT_EXITED_NORMALLY = 302
    CANNOT_SELECT = 303
    CANNOT_WAITPID = 304
    TABLE_WAS_NOT_DROPPED = 305
    TOO_DEEP_RECURSION = 306
    TOO_MANY_BYTES = 307
    UNEXPECTED_NODE_IN_ZOOKEEPER = 308
    FUNCTION_CANNOT_HAVE_PARAMETERS = 309
    INVALID_CONFIG_PARAMETER = 318
    UNKNOWN_STATUS_OF_INSERT = 319
    VALUE_IS_OUT_OF_RANGE_OF_DATA_TYPE = 321
    UNKNOWN_DATABASE_ENGINE = 336
    UNFINISHED = 341
    METADATA_MISMATCH = 342
    SUPPORT_IS_DISABLED = 344
    TABLE_DIFFERS_TOO_MUCH = 345
    CANNOT_CONVERT_CHARSET = 346
    CANNOT_LOAD_CONFIG = 347
    CANNOT_INSERT_NULL_IN_ORDINARY_COLUMN = 349
    AMBIGUOUS_COLUMN_NAME = 352
    INDEX_OF_POSITIONAL_ARGUMENT_IS_OUT_OF_RANGE = 353
    ZLIB_INFLATE_FAILED = 354
    ZLIB_DEFLATE_FAILED = 355
    INTO_OUTFILE_NOT_ALLOWED = 358
    TABLE_SIZE_EXCEEDS_MAX_DROP_SIZE_LIMIT = 359
    CANNOT_CREATE_CHARSET_CONVERTER = 360
    SEEK_POSITION_OUT_OF_BOUND = 361
    CURRENT_WRITE_BUFFER_IS_EXHAUSTED = 362
    CANNOT_CREATE_IO_BUFFER = 363
    RECEIVED_ERROR_TOO_MANY_REQUESTS = 364
    SIZES_OF_NESTED_COLUMNS_ARE_INCONSISTENT = 366
    ALL_REPLICAS_ARE_STALE = 369
    DATA_TYPE_CANNOT_BE_USED_IN_TABLES = 370
    INCONSISTENT_CLUSTER_DEFINITION = 371
    SESSION_NOT_FOUND = 372
    SESSION_IS_LOCKED = 373
    INVALID_SESSION_TIMEOUT = 374
    CANNOT_DLOPEN = 375
    CANNOT_PARSE_UUID = 376
    ILLEGAL_SYNTAX_FOR_DATA_TYPE = 377
    DATA_TYPE_CANNOT_HAVE_ARGUMENTS = 378
    CANNOT_KILL = 380
    HTTP_LENGTH_REQUIRED = 381
    CANNOT_LOAD_CATBOOST_MODEL = 382
    CANNOT_APPLY_CATBOOST_MODEL = 383
    PART_IS_TEMPORARILY_LOCKED = 384
    MULTIPLE_STREAMS_REQUIRED = 385
    NO_COMMON_TYPE = 386
    DICTIONARY_ALREADY_EXISTS = 387
    CANNOT_ASSIGN_OPTIMIZE = 388
    INSERT_WAS_DEDUPLICATED = 389
    CANNOT_GET_CREATE_TABLE_QUERY = 390
    EXTERNAL_LIBRARY_ERROR = 391
    QUERY_IS_PROHIBITED = 392
    THERE_IS_NO_QUERY = 393
    QUERY_WAS_CANCELLED = 394
    FUNCTION_THROW_IF_VALUE_IS_NON_ZERO = 395
    TOO_MANY_ROWS_OR_BYTES = 396
    QUERY_IS_NOT_SUPPORTED_IN_MATERIALIZED_VIEW = 397
    UNKNOWN_MUTATION_COMMAND = 398
    FORMAT_IS_NOT_SUITABLE_FOR_OUTPUT = 399
    CANNOT_STAT = 400
    FEATURE_IS_NOT_ENABLED_AT_BUILD_TIME = 401
    CANNOT_IOSETUP = 402
    INVALID_JOIN_ON_EXPRESSION = 403
    BAD_ODBC_CONNECTION_STRING = 404
    TOP_AND_LIMIT_TOGETHER = 406
    DECIMAL_OVERFLOW = 407
    BAD_REQUEST_PARAMETER = 408
    EXTERNAL_SERVER_IS_NOT_RESPONDING = 410
    PTHREAD_ERROR = 411
    NETLINK_ERROR = 412
    CANNOT_SET_SIGNAL_HANDLER = 413
    ALL_REPLICAS_LOST = 415
    REPLICA_STATUS_CHANGED = 416
    EXPECTED_ALL_OR_ANY = 417
    UNKNOWN_JOIN = 418
    MULTIPLE_ASSIGNMENTS_TO_COLUMN = 419
    CANNOT_UPDATE_COLUMN = 420
    CANNOT_ADD_DIFFERENT_AGGREGATE_STATES = 421
    UNSUPPORTED_URI_SCHEME = 422
    CANNOT_GETTIMEOFDAY = 423
    CANNOT_LINK = 424
    SYSTEM_ERROR = 425
    CANNOT_COMPILE_REGEXP = 427
    FAILED_TO_GETPWUID = 429
    MISMATCHING_USERS_FOR_PROCESS_AND_DATA = 430
    ILLEGAL_SYNTAX_FOR_CODEC_TYPE = 431
    UNKNOWN_CODEC = 432
    ILLEGAL_CODEC_PARAMETER = 433
    CANNOT_PARSE_PROTOBUF_SCHEMA = 434
    NO_COLUMN_SERIALIZED_TO_REQUIRED_PROTOBUF_FIELD = 435
    PROTOBUF_BAD_CAST = 436
    PROTOBUF_FIELD_NOT_REPEATED = 437
    DATA_TYPE_CANNOT_BE_PROMOTED = 438
    CANNOT_SCHEDULE_TASK = 439
    INVALID_LIMIT_EXPRESSION = 440
    CANNOT_PARSE_DOMAIN_VALUE_FROM_STRING = 441
    BAD_DATABASE_FOR_TEMPORARY_TABLE = 442
    NO_COLUMNS_SERIALIZED_TO_PROTOBUF_FIELDS = 443
    UNKNOWN_PROTOBUF_FORMAT = 444
    CANNOT_MPROTECT = 445
    FUNCTION_NOT_ALLOWED = 446
    HYPERSCAN_CANNOT_SCAN_TEXT = 447
    BROTLI_READ_FAILED = 448
    BROTLI_WRITE_FAILED = 449
    BAD_TTL_EXPRESSION = 450
    BAD_TTL_FILE = 451
    SETTING_CONSTRAINT_VIOLATION = 452
    MYSQL_CLIENT_INSUFFICIENT_CAPABILITIES = 453
    OPENSSL_ERROR = 454
    SUSPICIOUS_TYPE_FOR_LOW_CARDINALITY = 455
    UNKNOWN_QUERY_PARAMETER = 456
    BAD_QUERY_PARAMETER = 457
    CANNOT_UNLINK = 458
    CANNOT_SET_THREAD_PRIORITY = 459
    CANNOT_CREATE_TIMER = 460
    CANNOT_SET_TIMER_PERIOD = 461
    CANNOT_FCNTL = 463
    CANNOT_PARSE_ELF = 464
    CANNOT_PARSE_DWARF = 465
    INSECURE_PATH = 466
    CANNOT_PARSE_BOOL = 467
    CANNOT_PTHREAD_ATTR = 468
    VIOLATED_CONSTRAINT = 469
    QUERY_IS_NOT_SUPPORTED_IN_LIVE_VIEW = 470
    INVALID_SETTING_VALUE = 471
    READONLY_SETTING = 472
    DEADLOCK_AVOIDED = 473
    INVALID_TEMPLATE_FORMAT = 474
    INVALID_WITH_FILL_EXPRESSION = 475
    WITH_TIES_WITHOUT_ORDER_BY = 476
    INVALID_USAGE_OF_INPUT = 477
    UNKNOWN_POLICY = 478
    UNKNOWN_DISK = 479
    UNKNOWN_PROTOCOL = 480
    PATH_ACCESS_DENIED = 481
    DICTIONARY_ACCESS_DENIED = 482
    TOO_MANY_REDIRECTS = 483
    INTERNAL_REDIS_ERROR = 484
    CANNOT_GET_CREATE_DICTIONARY_QUERY = 487
    INCORRECT_DICTIONARY_DEFINITION = 489
    CANNOT_FORMAT_DATETIME = 490
    UNACCEPTABLE_URL = 491
    ACCESS_ENTITY_NOT_FOUND = 492
    ACCESS_ENTITY_ALREADY_EXISTS = 493
    ACCESS_STORAGE_READONLY = 495
    QUOTA_REQUIRES_CLIENT_KEY = 496
    ACCESS_DENIED = 497
    LIMIT_BY_WITH_TIES_IS_NOT_SUPPORTED = 498
    S3_ERROR = 499
    AZURE_BLOB_STORAGE_ERROR = 500
    CANNOT_CREATE_DATABASE = 501
    CANNOT_SIGQUEUE = 502
    AGGREGATE_FUNCTION_THROW = 503
    FILE_ALREADY_EXISTS = 504
    UNABLE_TO_SKIP_UNUSED_SHARDS = 507
    UNKNOWN_ACCESS_TYPE = 508
    INVALID_GRANT = 509
    CACHE_DICTIONARY_UPDATE_FAIL = 510
    UNKNOWN_ROLE = 511
    SET_NON_GRANTED_ROLE = 512
    UNKNOWN_PART_TYPE = 513
    ACCESS_STORAGE_FOR_INSERTION_NOT_FOUND = 514
    INCORRECT_ACCESS_ENTITY_DEFINITION = 515
    AUTHENTICATION_FAILED = 516
    CANNOT_ASSIGN_ALTER = 517
    CANNOT_COMMIT_OFFSET = 518
    NO_REMOTE_SHARD_AVAILABLE = 519
    CANNOT_DETACH_DICTIONARY_AS_TABLE = 520
    ATOMIC_RENAME_FAIL = 521
    UNKNOWN_ROW_POLICY = 523
    ALTER_OF_COLUMN_IS_FORBIDDEN = 524
    INCORRECT_DISK_INDEX = 525
    NO_SUITABLE_FUNCTION_IMPLEMENTATION = 527
    CASSANDRA_INTERNAL_ERROR = 528
    NOT_A_LEADER = 529
    CANNOT_CONNECT_RABBITMQ = 530
    CANNOT_FSTAT = 531
    LDAP_ERROR = 532
    UNKNOWN_RAID_TYPE = 535
    CANNOT_RESTORE_FROM_FIELD_DUMP = 536
    ILLEGAL_MYSQL_VARIABLE = 537
    MYSQL_SYNTAX_ERROR = 538
    CANNOT_BIND_RABBITMQ_EXCHANGE = 539
    CANNOT_DECLARE_RABBITMQ_EXCHANGE = 540
    CANNOT_CREATE_RABBITMQ_QUEUE_BINDING = 541
    CANNOT_REMOVE_RABBITMQ_EXCHANGE = 542
    UNKNOWN_MYSQL_DATATYPES_SUPPORT_LEVEL = 543
    ROW_AND_ROWS_TOGETHER = 544
    FIRST_AND_NEXT_TOGETHER = 545
    NO_ROW_DELIMITER = 546
    INVALID_RAID_TYPE = 547
    UNKNOWN_VOLUME = 548
    DATA_TYPE_CANNOT_BE_USED_IN_KEY = 549
    UNRECOGNIZED_ARGUMENTS = 552
    LZMA_STREAM_ENCODER_FAILED = 553
    LZMA_STREAM_DECODER_FAILED = 554
    ROCKSDB_ERROR = 555
    SYNC_MYSQL_USER_ACCESS_ERROR = 556
    UNKNOWN_UNION = 557
    EXPECTED_ALL_OR_DISTINCT = 558
    INVALID_GRPC_QUERY_INFO = 559
    ZSTD_ENCODER_FAILED = 560
    ZSTD_DECODER_FAILED = 561
    TLD_LIST_NOT_FOUND = 562
    CANNOT_READ_MAP_FROM_TEXT = 563
    INTERSERVER_SCHEME_DOESNT_MATCH = 564
    TOO_MANY_PARTITIONS = 565
    CANNOT_RMDIR = 566
    DUPLICATED_PART_UUIDS = 567
    RAFT_ERROR = 568
    MULTIPLE_COLUMNS_SERIALIZED_TO_SAME_PROTOBUF_FIELD = 569
    DATA_TYPE_INCOMPATIBLE_WITH_PROTOBUF_FIELD = 570
    DATABASE_REPLICATION_FAILED = 571
    TOO_MANY_QUERY_PLAN_OPTIMIZATIONS = 572
    EPOLL_ERROR = 573
    DISTRIBUTED_TOO_MANY_PENDING_BYTES = 574
    UNKNOWN_SNAPSHOT = 575
    KERBEROS_ERROR = 576
    INVALID_SHARD_ID = 577
    INVALID_FORMAT_INSERT_QUERY_WITH_DATA = 578
    INCORRECT_PART_TYPE = 579
    CANNOT_SET_ROUNDING_MODE = 580
    TOO_LARGE_DISTRIBUTED_DEPTH = 581
    NO_SUCH_PROJECTION_IN_TABLE = 582
    ILLEGAL_PROJECTION = 583
    PROJECTION_NOT_USED = 584
    CANNOT_PARSE_YAML = 585
    CANNOT_CREATE_FILE = 586
    CONCURRENT_ACCESS_NOT_SUPPORTED = 587
    DISTRIBUTED_BROKEN_BATCH_INFO = 588
    DISTRIBUTED_BROKEN_BATCH_FILES = 589
    CANNOT_SYSCONF = 590
    SQLITE_ENGINE_ERROR = 591
    DATA_ENCRYPTION_ERROR = 592
    ZERO_COPY_REPLICATION_ERROR = 593
    BZIP2_STREAM_DECODER_FAILED = 594
    BZIP2_STREAM_ENCODER_FAILED = 595
    INTERSECT_OR_EXCEPT_RESULT_STRUCTURES_MISMATCH = 596
    NO_SUCH_ERROR_CODE = 597
    BACKUP_ALREADY_EXISTS = 598
    BACKUP_NOT_FOUND = 599
    BACKUP_VERSION_NOT_SUPPORTED = 600
    BACKUP_DAMAGED = 601
    NO_BASE_BACKUP = 602
    WRONG_BASE_BACKUP = 603
    BACKUP_ENTRY_ALREADY_EXISTS = 604
    BACKUP_ENTRY_NOT_FOUND = 605
    BACKUP_IS_EMPTY = 606
    CANNOT_RESTORE_DATABASE = 607
    CANNOT_RESTORE_TABLE = 608
    FUNCTION_ALREADY_EXISTS = 609
    CANNOT_DROP_FUNCTION = 610
    CANNOT_CREATE_RECURSIVE_FUNCTION = 611
    POSTGRESQL_CONNECTION_FAILURE = 614
    CANNOT_ADVISE = 615
    UNKNOWN_READ_METHOD = 616
    LZ4_ENCODER_FAILED = 617
    LZ4_DECODER_FAILED = 618
    POSTGRESQL_REPLICATION_INTERNAL_ERROR = 619
    QUERY_NOT_ALLOWED = 620
    CANNOT_NORMALIZE_STRING = 621
    CANNOT_PARSE_CAPN_PROTO_SCHEMA = 622
    CAPN_PROTO_BAD_CAST = 623
    BAD_FILE_TYPE = 624
    IO_SETUP_ERROR = 625
    CANNOT_SKIP_UNKNOWN_FIELD = 626
    BACKUP_ENGINE_NOT_FOUND = 627
    OFFSET_FETCH_WITHOUT_ORDER_BY = 628
    HTTP_RANGE_NOT_SATISFIABLE = 629
    HAVE_DEPENDENT_OBJECTS = 630
    UNKNOWN_FILE_SIZE = 631
    UNEXPECTED_DATA_AFTER_PARSED_VALUE = 632
    QUERY_IS_NOT_SUPPORTED_IN_WINDOW_VIEW = 633
    MONGODB_ERROR = 634
    CANNOT_POLL = 635
    CANNOT_EXTRACT_TABLE_STRUCTURE = 636
    INVALID_TABLE_OVERRIDE = 637
    SNAPPY_UNCOMPRESS_FAILED = 638
    SNAPPY_COMPRESS_FAILED = 639
    NO_HIVEMETASTORE = 640
    CANNOT_APPEND_TO_FILE = 641
    CANNOT_PACK_ARCHIVE = 642
    CANNOT_UNPACK_ARCHIVE = 643
    NUMBER_OF_DIMENSIONS_MISMATCHED = 645
    CANNOT_BACKUP_TABLE = 647
    WRONG_DDL_RENAMING_SETTINGS = 648
    INVALID_TRANSACTION = 649
    SERIALIZATION_ERROR = 650
    CAPN_PROTO_BAD_TYPE = 651
    ONLY_NULLS_WHILE_READING_SCHEMA = 652
    CANNOT_PARSE_BACKUP_SETTINGS = 653
    WRONG_BACKUP_SETTINGS = 654
    FAILED_TO_SYNC_BACKUP_OR_RESTORE = 655
    UNKNOWN_STATUS_OF_TRANSACTION = 659
    HDFS_ERROR = 660
    CANNOT_SEND_SIGNAL = 661
    FS_METADATA_ERROR = 662
    INCONSISTENT_METADATA_FOR_BACKUP = 663
    ACCESS_STORAGE_DOESNT_ALLOW_BACKUP = 664
    CANNOT_CONNECT_NATS = 665
    NOT_INITIALIZED = 667
    INVALID_STATE = 668
    NAMED_COLLECTION_DOESNT_EXIST = 669
    NAMED_COLLECTION_ALREADY_EXISTS = 670
    NAMED_COLLECTION_IS_IMMUTABLE = 671
    INVALID_SCHEDULER_NODE = 672
    RESOURCE_ACCESS_DENIED = 673
    RESOURCE_NOT_FOUND = 674
    CANNOT_PARSE_IPV4 = 675
    CANNOT_PARSE_IPV6 = 676
    THREAD_WAS_CANCELED = 677
    IO_URING_INIT_FAILED = 678
    IO_URING_SUBMIT_ERROR = 679
    MIXED_ACCESS_PARAMETER_TYPES = 690
    UNKNOWN_ELEMENT_OF_ENUM = 691
    TOO_MANY_MUTATIONS = 692
    AWS_ERROR = 693
    ASYNC_LOAD_CYCLE = 694
    ASYNC_LOAD_FAILED = 695
    ASYNC_LOAD_CANCELED = 696
    CANNOT_RESTORE_TO_NONENCRYPTED_DISK = 697
    INVALID_REDIS_STORAGE_TYPE = 698
    INVALID_REDIS_TABLE_STRUCTURE = 699
    USER_SESSION_LIMIT_EXCEEDED = 700
    CLUSTER_DOESNT_EXIST = 701
    CLIENT_INFO_DOES_NOT_MATCH = 702
    INVALID_IDENTIFIER = 703
    QUERY_CACHE_USED_WITH_NONDETERMINISTIC_FUNCTIONS = 704
    TABLE_NOT_EMPTY = 705
    LIBSSH_ERROR = 706
    GCP_ERROR = 707
    KEEPER_EXCEPTION = 999
    POCO_EXCEPTION = 1000
    STD_EXCEPTION = 1001
    UNKNOWN_EXCEPTION = 1002
end
